Sprint_5
nniktina/Sprint_5 pull request #2
Opened 2023-11-30 11:14 UTC by nniktina

(cherry picked from commit 20adf3e0520acd0916066a2539a805987a6ba920)

2023-12-02 19:21 UTC, kadirovgm requested changes

2023-12-02 19:21 UTC, kadirovgm commented on tests/data_for_test.py
> +user_email = 'nastya_n_3_111@yandex.ru' # уже зарегистрированный пользователь
Можно лучше: советую разделить тестовые данные в классы, сгруппировать их по цели использования, например UserCredits(), Urls() итд

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    driver = webdriver.Chrome()
Нужно исправить: необходимо добавить самую важную фикстуру, отвечающую за setup и teardown

ты в каждом тесте их прописываешь - это не корректно, мы должны избегать всякого повторения в коде

пример:
```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()
```

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    driver.quit()
Нужно исправить: выше написал, что teardown метод нужно поместить в фикстуру вместе с setup

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    driver.find_element(By.XPATH, ".//button[text()='Войти в аккаунт']").click()
Можно лучше: предлагаю все локаторы держать в одном месте, например в файле locators.py или выносить локаторы в начало файла - таким образом мы сможем переиспользовать локаторы в тестах и, при их изменении, нам придется подправить лишь в одном месте, а не в каждом тесте

2023-12-02 19:21 UTC, kadirovgm commented on tests/data_for_test.py
нужно исправить: в папке tests давай держать только файлы с тестами (и еще conftest.py), а все остальное лучше выносить за пределы данной папки

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    WebDriverWait(driver, 5).until(expected_conditions.url_to_be('https://stellarburgers.nomoreparties.site/login'))
нужно исправить: почему эту ссылку не берешь из data_for_test.py?

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(data_for_test.user_email)
нужно исправить: здесь и ниже по всему коду

локаторы типа такого (длинные, громоздкие, и завязанные на большом количестве нестабильных аттрибутах элемента) часто нестабильны и падают при малейшем изменении кода фронтенда. Поэтому, пожалуйста, перечитай раздел нашего курса про локаторы, и напиши более стабильные и короткие локаторы

конкретно надо избавляться от вложенных div-ов

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    assert driver.current_url == data_for_test.main_page_url
Можно лучше:  проверка того, что URL поменялся на <url> не гарантирует, что страница прогрузилась, поэтому стоит ориентироваться на какие-либо элементы страницы, чекать, что они появились и отображаются корректно

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(data_for_test.user_email)
Можно лучше: как видишь строки для авторизации у тебя повторяются в нескольких тестах - в таком случае предлагаю создать функцию helper, которая будет заполнять поля авторизации

во всех тестах, где нужно, можно переиспользовать эту функцию и сократить код

2023-12-02 19:21 UTC, kadirovgm commented on tests/test_logout.py
> +    assert driver.current_url == data_for_test.login_page_url
нужно исправить: как эта проверка гарантирует, что логаут успешен? предлагаю опираться не на URL, а, например, на наличие кнопки "Вход" после логаута

2023-12-04 08:46 UTC, nniktina commented on tests/data_for_test.py
> +user_email = 'nastya_n_3_111@yandex.ru' # уже зарегистрированный пользователь
fixed

2023-12-04 08:46 UTC, nniktina commented on tests/test_login.py
> +    driver = webdriver.Chrome()
Вынесла в отдельную фикстуру

2023-12-04 08:46 UTC, nniktina commented on tests/test_login.py
> +    driver.quit()
Вынесла в отдельную фикстуру

2023-12-04 08:47 UTC, nniktina commented on tests/test_login.py
> +    driver.find_element(By.XPATH, ".//button[text()='Войти в аккаунт']").click()
Сделала новый файл locators.py и вынесла туда все локаторы из тестов (как я поняла, можно там тоже сделать разделение на классы, но я это опустила)

2023-12-04 08:48 UTC, nniktina commented on tests/data_for_test.py
исправлено

2023-12-04 08:48 UTC, nniktina commented on tests/test_login.py
> +    WebDriverWait(driver, 5).until(expected_conditions.url_to_be('https://stellarburgers.nomoreparties.site/login'))
Наверное проглядела, исправила :)

2023-12-04 08:49 UTC, nniktina commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(data_for_test.user_email)
Избавилась от вложенности (но есть пара локаторов, которые обращаются через following-sibling::)

2023-12-04 08:49 UTC, nniktina commented on tests/test_login.py
> +    assert driver.current_url == data_for_test.main_page_url
избавилась везде от проверки на url

2023-12-04 08:50 UTC, nniktina commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(data_for_test.user_email)
завела hepler в тестовых классах, где заполнение одинаковых полей используется более чем в 1-ом тесте

2023-12-04 08:50 UTC, nniktina commented on tests/test_logout.py
> +    assert driver.current_url == data_for_test.login_page_url
Избавилась в тестах от проверок на url

2023-12-04 22:43 UTC, kadirovgm commented on tests/test_login.py
> +    driver.find_element(By.XPATH, './/fieldset[1]/div/div/input').send_keys(data_for_test.user_email)
> Избавилась от вложенности (но есть пара локаторов, которые обращаются через following-sibling::)

это нормально

2023-12-04 22:45 UTC, kadirovgm approved these changes

2023-12-04 22:45 UTC, kadirovgm commented on data.py
> +
отлично!

2023-12-04 22:45 UTC, kadirovgm commented on locators.py
> +drag_the_bread = "ul.BurgerConstructor_basket__list__l9dp_" # блок с перетягиванием булочек на главной странице
локаторы стали лучше, молодец!

2023-12-04 22:45 UTC, kadirovgm commented on tests/conftest.py
> +def driver():
супер

2023-12-04 22:45 UTC, kadirovgm commented on tests/test_login.py
> +    def test_login_from_main_page_successful(self, driver):
тесты стали чище)

2023-12-05 05:44 UTC, merged